### PR TITLE
Fix issue #505

### LINKED ISSUE #505: Error message rewriting is lost for runtime errors.
We've lost error message rewriting in runtime errors, as part of migrating the rewriting code to the server.  For example, when I lose at https://code.world/#PWCzFEaAgOuBeBUKcEPiVzw, I get:

    GAME OVER
    CallStack (from HasCallStack):
      error, called at Line 34, Column 12 in main:Main

There used to be rules that would replace "main:Main" with "your program", and also "CallStack (from HasCallStack):" with "When evaluating:".  Now that those are bundled into the compiler, they do not get applied to runtime errors. Oops!

The solution is going to be a little ugly.  Perhaps it's to move error sanitizing into a runtime library, which can be compiled by both GHCJS and GHC?

### PR DESCRIPTION
**Pull request by pranjaltale16**
This PR fix #505.

### CODE REVIEW

**Comment by pranjaltale16** [comment]
I think still exceptions are caught in codeworld-api only.
Changes are made but I'm not getting where is this going wrong. Messages are not getting sanitized.

File: codeworld-error-sanitizer/Setup.hs [hunk 1]
```diff
@@ -0,0 +1,2 @@
+import Distribution.Simple
```
Comment (cdsmith) [inline codeworld-error-sanitizer/Setup.hs]: Please add a license comment here.  Copy it from any other Haskell source file.

File: codeworld-error-sanitizer/codeworld-error-sanitizer.cabal [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+Author:              Chris Smith
+Maintainer:          cdsmith@gmail.com
+Copyright:           (c) 2017, The CodeWorld Authors
+Build-type:          Simple
+Cabal-version:       >=1.10
+
+Description:
+  Regex based error filter library for CodeWorld compiler 
+
+library
```
Comment (cdsmith) [inline codeworld-error-sanitizer/codeworld-error-sanitizer.cabal]: [nit] Please capitalize "library"

File: codeworld-base/src/Internal/CodeWorld.hs [hunk 3]
```diff
@@ -57,7 +68,7 @@ simulationOf (initial, step, draw) = do
     rs <- chooseRandoms
     CW.simulationOf (initial rs)
                     (\dt w -> step (w, fromDouble dt))
-                    (toCWPic . draw)
+                    (toCWPic . draw) `catch` reportError
```
Comment (cdsmith) [inline codeworld-base/src/Internal/CodeWorld.hs]: Please put the catch on the next line (but indented relative to the `do` block).

File: codeworld-base/src/Internal/CodeWorld.hs [hunk 4]
```diff
@@ -69,7 +80,7 @@ interactionOf (initial, step, event, draw) = do
     CW.interactionOf (initial rs)
                      (\dt w -> step (w, fromDouble dt))
                      (\ev w -> event (w, fromCWEvent ev))
-                     (toCWPic . draw)
+                     (toCWPic . draw) `catch` reportError
```
Comment (cdsmith) [inline codeworld-base/src/Internal/CodeWorld.hs]: Catch on the next line (same as above)

File: codeworld-base/src/Internal/CodeWorld.hs [hunk 5]
```diff
@@ -85,11 +96,14 @@ collaborationOf (players, initial, step, event, picture) =
         (initial . randomsFrom)
         (\dt state -> step (state, fromDouble dt))
         (\player ev state -> event (state, fromCWEvent ev, fromInt player + 1))
-        (\player state -> toCWPic (picture (state, fromInt player + 1)))
+        (\player state -> toCWPic (picture (state, fromInt player + 1))) `catch` reportError
```
Comment (cdsmith) [inline codeworld-base/src/Internal/CodeWorld.hs]: Catch on the next line (same as above)

File: codeworld-error-sanitizer/Setup.hs [hunk 6]
```diff
@@ -1,2 +1,21 @@
+{-# LANGUAGE LambdaCase        #-}
```
Comment (cdsmith) [inline codeworld-error-sanitizer/Setup.hs]: You don't need these language pragmas.

File: codeworld-base/src/Internal/CodeWorld.hs [hunk 7]
```diff
@@ -68,7 +68,8 @@ simulationOf (initial, step, draw) = do
     rs <- chooseRandoms
     CW.simulationOf (initial rs)
                     (\dt w -> step (w, fromDouble dt))
-                    (toCWPic . draw) `catch` reportError
+                    (toCWPic . draw)
+                    `catch` reportError
```
Comment (cdsmith) [inline codeworld-base/src/Internal/CodeWorld.hs]: Sorry, I should have been clearer.  I'm trying to avoid the catch looking like a parameter, so let's please indent less than the parameters.  Four spaces past the do block indent would be consistent.

File: codeworld-error-sanitizer/Setup.hs (hunk 6 above)
Comment (pranjaltale16) [reply codeworld-error-sanitizer/Setup.hs]: Sorry for this.

**Comment by cdsmith** [comment]
Thanks!
